package May20Homework;
/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1
 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */
public class EulerQ2 {
    public static void main(String[] args) {
        int FibonnaciVal = 0;
        int OLDERVal = 0;
        int oldVal = 1;
        int sum = 0;
        for(int i = 1; FibonnaciVal < 4000000; i+=1){
          FibonnaciVal = oldVal + OLDERVal;
       //System.out.println(FibonnaciVal);
          OLDERVal = oldVal;
          oldVal = FibonnaciVal;
          if(FibonnaciVal % 2 == 0){
            sum += FibonnaciVal;
          }
          System.out.println(sum);
      //   System.out.println(FibonnaciVal);
        }
    }
    
}
